name: Run-Me
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
  
  
jobs:
  #Testing
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Ngrok
        run: |
            apt upgrade
            apt update
            apt instal unzip
            apt install curl
            curl -S https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip
            unzip ngrok-stable-linux-arm.zip
            
          
