name: Run-Me
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
  
  
jobs:
  #Testing
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Installing Ngrok
        run: |
            echo "Nuuu"
